// Select DOM elements
var form = document.getElementById("qr-form");
var linkInput = document.getElementById("link-input");
var sizeInput = document.getElementById("size-input");
var downloadContainer = document.querySelector(".qrcodeDownload-container")
var qrcodeContainer = document.getElementById("qrcode");
var downloadBtn = document.getElementById("download-btn");
var canvas = document.querySelector("#qrcode canvas");

// Generate the QR code when the form is submitted
form.addEventListener("submit", function(event) {
  // Prevent form submission
  event.preventDefault(); 
  
  // Clear the previous QR code
  qrcodeContainer.innerHTML = '';

  var qrcode = new QRCode(qrcodeContainer, {
    text: linkInput.value,
    width: sizeInput.value,
    height: sizeInput.value,
    colorDark: "#000000",
    colorLight: "#ffffff",
    correctLevel: QRCode.CorrectLevel.H
  });
  
  // Show Container of QRCode and Download button
  downloadContainer.style.display = "flex";
});

// Download the QR code when clicking on the download button
downloadBtn.addEventListener("click", function() {
 // Create a temporary canvas
var tempCanvas = document.createElement("canvas");
tempCanvas.width = qrcodeContainer.offsetWidth;
tempCanvas.height = qrcodeContainer.offsetHeight;

// Copy the content of the canvas generated by QRCode.js into the temporary canvas
var ctx = tempCanvas.getContext("2d");
ctx.drawImage(qrcodeContainer.querySelector("canvas"), 0, 0);

// Download the QR code as a PNG image
downloadBtn.href = tempCanvas.toDataURL("image/png");
downloadBtn.download = "qr-code.png";
});

